Algoritmo "Escolha_Dias"

Var
   dias: inteiro

Inicio
   Escreval("Escolha um número (1-7)")
   Leia(dias)

   //Estrutura de decisão
   Escolha dias
      Caso 1
      Escreval("Hoje será seu dia de sorte!")
      Caso 2
      Escreval("Confie mais na sua intuição hoje.")
      Caso 3
      Escreval("Uma oportunidade inesperada pode mudar seu dia.")
      Caso 4
      Escreval("Evite agir por impulso nas próximas horas.")
      Caso 5
      Escreval("Pequenos passos hoje trarão grandes resultados amanhã.")
      Caso 6
      Escreval("Uma conversa simples pode revelar algo importante.")
      Caso 7
      Escreval("Seu esforço silencioso está mais perto de ser recompensado.")
   Outrocaso
      Escreva("Número inválido! Digite um número de 1 a 7.")
   FimEscolha

Fimalgoritmo